version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  monstr:
    build: .
    image: "docker.io/0xjsi/monstr-rofl"
    command: python monstr_relay.py
    ports:
      - "8082:8082"


volumes:
  mongodb_data:
