services:
  mongodb:
    image: mongo:latest
    container_name: rofl_mongodb
    #platform: linux/amd64
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: roflchats
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: rofl_mongo_express
    #platform: linux/amd64
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  rofl-fun:
    build: .
    image: "docker.io/0xjsi/rofl-nostr-app"
    platform: linux/amd64
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - monstr

  monstr:
    build: .
    image: "docker.io/0xjsi/monstr-rofl"
    command: python monstr_relay.py
    ports:
      - "8082:8082"

volumes:
  mongodb_data:
  rofl_fun:
  monstr: